name: Deploy to K3s on VPS

# Gatilho: Executa este workflow sempre que houver um push na branch 'main'
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest # O workflow roda em uma máquina virtual do GitHub

    steps:
      # 1. Baixa o código do seu repositório para a máquina do GitHub Actions
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Instala e configura o kubectl decodificando o secret
      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          # Decodifica o secret (que deve estar em Base64) e salva no arquivo de configuração
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
        
      # (Opcional, mas recomendado para depuração) Verifica o conteúdo do arquivo gerado
      - name: Debug Kubeconfig Content
        run: |
          echo "--- Verificando o conteúdo do kubeconfig (sem dados sensíveis) ---"
          # O comando 'get-clusters' é seguro e confirma que o arquivo é válido
          kubectl config get-clusters
          echo "----------------------------------------------------------------"

      # 3. Aplica as configurações do Kubernetes no seu cluster
      - name: Deploy to K3s
        run: |
          # Este comando assume que seus arquivos de deploy estão na pasta 'k8s/'
          kubectl apply -f k8s/
          
          echo "Verificando o status dos pods..."
          sleep 10 # Dá um tempo para os pods começarem a subir
          kubectl get pods
