name: Deploy to K3s on VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Instala e configura o kubectl usando o secret DIRETAMENTE
      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          # Salva o conteúdo do secret diretamente, SEM decodificar
          echo "${{ secrets.KUBE_CONFIG_DATA }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
        
      # 3. Aplica as configurações do Kubernetes no seu cluster
      - name: Deploy to K3s
        run: |
          # O passo abaixo substitui a tag da imagem no seu arquivo de deployment
          # para garantir que a nova imagem seja usada.
          echo "Atualizando a imagem para: ghcr.io/${{ github.repository }}:${{ github.sha }}"
          sed -i "s|image:.*|image: ghcr.io/${{ github.repository }}:${{ github.sha }}|g" k8s/deployment.yaml
          
          # Aplica os manifestos ao cluster
          kubectl apply -f k8s/
          
          echo "Verificando o status do deploy..."
          sleep 15 # Dá um tempo para o Kubernetes processar as mudanças
          kubectl get pods
          kubectl get services
